name: Simple CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: todos
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - id: run_tests
        name: Run tests
        run: just integration_tests
